### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by Lebmont27** [e-sim-python/eSim#1]
Hey, first of all thank you for the amazing work you have put in here.
But despite many efforts and hours to try to fix what isn't working alone, i can't figure what's wrong.
I mean i know that the issue is connecting to the cluster but i have no idea what to do more than i have already done.

That's what i get : 

cluster1-shard-00-00.aone7.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997),cluster1-shard-00-02.aone7.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997),cluster1-shard-00-01.aone7.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997), Timeout: 30s, Topology Description: <TopologyDescription id: 62365c2571b13f092f2d0798, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster1-shard-00-00.aone7.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster1-shard-00-00.aone7.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')>, <ServerDescription ('cluster1-shard-00-01.aone7.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster1-shard-00-01.aone7.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')>, <ServerDescription ('cluster1-shard-00-02.aone7.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster1-shard-00-02.aone7.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')>]>

Thank you in advance

**Comment by e-sim-python** [comment]
Hey, @Lebmont27. Please try to follow [those instructions](https://github.com/e-sim-python/eSim#setup) very carefully.
If you already did that:
According to [this answer](https://stackoverflow.com/a/67748177)  you should change [this line](https://github.com/e-sim-python/eSim/blob/main/bot.py#L41) into `bot.client = AsyncIOMotorClient(environ['database_url'], tls=True, tlsAllowInvalidCertificates=True)`.

Btw, I am planning to make the MongoDB thing optional one day.

**Comment by Lebmont27** [comment]
I've followed the steps several times, tried to uninstall everything but it seems i can't make the connection to the cluster part work :(

**Comment by Lebmont27** [comment]
I only managed to run it on local but not hosted

**Comment by Lebmont27** [comment]
Well it seems to be working on the local network, but i have an issue with the hunt fonction, it works well, travels to the good location, but then it crashes at the time to hit.

**Comment by e-sim-python** [comment]
Do you get any errors?

**Comment by Lebmont27** [comment]
Yeah that's what i got after the travel : 
Traceback (most recent call last):
  File "C:\Users\adrie\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\Users\adrie\OneDrive\Bureau\e-sim discord bot\eSim-main\War.py", line 518, in hunt
    await hunting("attacker", aDMG, dDMG < max_dmg_for_bh)
  File "c:\Users\adrie\OneDrive\Bureau\e-sim discord bot\eSim-main\War.py", line 493, in hunting
    c = await check(side.title(), damage_done, should_continue)
  File "c:\Users\adrie\OneDrive\Bureau\e-sim discord bot\eSim-main\War.py", line 467, in check
    if battleScore["remainingTimeInSeconds"] > start_time:
  File "src\lxml\etree.pyx", line 1174, in lxml.etree._Element.__getitem__
TypeError: 'str' object cannot be interpreted as an integer

**Comment by e-sim-python** [comment]
Alright, I have made some changes.
Please let me know if the problem is solved.
