### ISSUE TITLE
eqs function error

### ISSUE THREAD

**Issue by zazo14** [e-sim-python/eSim#4]
File "/home/user/eSim-main/Info.py", line 53, in eqs
    await ctx.send(embed=embed)
  File "/usr/local/lib/python3.7/dist-packages/discord/abc.py", line 1067, in send
    message_reference=reference)
  File "/usr/local/lib/python3.7/dist-packages/discord/http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.fields.0.value: This field is required
In embed.fields.1.value: This field is required
In embed.fields.2.value: This field is required

Maybe it's due to having an empty inventory? I'm using it on debian minimal so it's kinda hard to debug :)

**Comment by e-sim-python** [comment]
@zazo14 yes, I didn't try to catch every possible error because it would consume too much of my time.
