### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by shekemo** [e-sim-python/eSim#5]
is this still available in android?

**Comment by shekemo** [comment]
some Script didn't working

**Comment by e-sim-python** [comment]
Can you elaborate?

**Comment by shekemo** [comment]
Yeah xd is this working at mobile xd i can only use one script at the same time and one server at the same time

**Comment by e-sim-python** [comment]
I have not tested it on mobile, but it should work just fine.
Maybe you are talking about the old version.
In the current one, you execute `bot.py` only, and it allows you to invoke all scripts in all servers at the same time.

Good luck :)

**Comment by shekemo** [comment]
Thank you

**Comment by shekemo** [comment]
so how do i setup this in mobile xd

**Comment by e-sim-python** [comment]
Check out this page: https://github.com/e-sim-python/eSim#readme

**Comment by shekemo** [comment]
it need pc?

**Comment by shekemo** [comment]
Bro and the auto bid in android doesn't workk

**Comment by shekemo** [comment]
pls if i need it how to use it or pls
