### ISSUE TITLE
Hello can u fix the auto hunt

### ISSUE THREAD

**Issue by shekemo** [e-sim-python/eSim#6]
can't auto hunt if q1 ticket?

**Comment by e-sim-python** [comment]
You can.
Type `.help hunt` in your channel and follow the guide.

For example, the command below will execute the hunt function with the following parameters: 
[max_dmg_for_bh=500000] [weapon_quality=5] [start_time=30] [ticket_quality=1]
`.hunt SOME_NICK 500k 5 30 1`
