### ISSUE TITLE
Auto bid 

### ISSUE THREAD

**Issue by shekemo** [e-sim-python/eSim#8]
![USER_SCOPED_TEMP_DATA_orca-image-1140592012](https://user-images.githubusercontent.com/82989096/183282115-49d22d26-a278-4008-80e1-fb227baa6be8.jpeg)

how is this gonna work sir.?
can u give me some examples

**Comment by e-sim-python** [comment]
Hey, @shekemo as I told you before, you are using the old version, which is no longer supported.
I suggest you install the [new version](https://github.com/e-sim-python/eSim#installation) (click the blue words and follow the instructions in installation + setup)

Good luck :)

**Comment by shekemo** [comment]
Is there From Android?

**Comment by shekemo** [comment]
I cant Create This new version my pc Broken

**Comment by shekemo** [comment]
This is hard no more for Android users

**Comment by e-sim-python** [comment]
It should work on Android, tho I did not test it.
What error do you get?

**Comment by shekemo** [comment]
Its already okey thank you

**Comment by shekemo** [comment]
is there any auto bid here like before?
